[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  testImplementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
  testRuntimeOnly "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  api "com.badlogicgames.gdx:gdx-bullet:$gdxVersion"
  api "com.badlogicgames.ashley:ashley:1.7.4"
  api "com.kotcrab.vis:vis-ui:$visuiVersion"
  api "de.javagl:jgltf-model:$jgltfVersion"
  api "com.esotericsoftware:kryo:$kryoVersion"
  implementation "org.slf4j:slf4j-api:2.0.18"
}
